### ISSUE TITLE
Problem with page numbers printing.

### ISSUE THREAD

**Issue by ndsergeev** [chewxy/SDIPUTS#5]
Hey, friends. In addition to previous issues, there problem with page number printing:
It works like "..., pp. 437–445."
But should prints "..., pp. 437–45." instead.

It seems that the easiest way is to rewrite the original file using regex lib. I'll try to code it using Python soon if you don't know how to program it in *.bst macro.

**Comment by chewxy** [comment]
Do send a PR. My slack/mattermost intergration was broken for a few months so I had not seen @brentonsmith 's PR ... but that's been fixed now

**Comment by ndsergeev** [comment]
Thank you for the update! It seems that the in-text comma problem disappeared, but page problem is still actual.
